const KEY="bookmarks";
const SAVE_DELAY=2000;
let bookmarkCache=null;
let saveTimer=null;
let savePromise=null;
let saveQueued=false;
chrome.runtime.onInstalled.addListener(async()=>{await chrome.sidePanel.setPanelBehavior({openPanelOnActionClick:true});});
async function getBookmarks(){if(bookmarkCache!==null)return bookmarkCache;const data=await chrome.storage.local.get(KEY);bookmarkCache=Array.isArray(data[KEY])?data[KEY].map(normalizeItem):[];return bookmarkCache;}
function cleanStoredImages(value){return[...new Set((Array.isArray(value)?value:[]).filter(src=>{try{const u=new URL(String(src));if(u.hostname.endsWith("abs.twimg.com"))return false;if(u.hostname.endsWith("video.twimg.com"))return false;if(u.hostname==="pbs.twimg.com"&&!/^\/(?:media|ext_tw_video_thumb|amplify_video_thumb|tweet_video_thumb)\//i.test(u.pathname))return false;return true;}catch{return false}}))];}
function normalizeItem(item){const collections=Array.isArray(item?.collections)?[...new Set(item.collections.filter(v=>v==="bookmark"||v==="like"))]:[];return{...item,images:cleanStoredImages(item?.images),collections:collections.length?collections:["bookmark"],tags:Array.isArray(item?.tags)?[...new Set(item.tags.map(t=>String(t).trim()).filter(Boolean))]:[]};}
function mergeStats(a={},b={}){const keys=["replies","reposts","likes","bookmarks","views"];return Object.fromEntries(keys.map(key=>[key,Math.max(Number(a[key]||0),Number(b[key]||0))]));}
function mergeItem(current,incoming){const a=normalizeItem(current),b=normalizeItem(incoming);return normalizeItem({...a,...b,text:b.text||a.text||"",displayName:b.displayName||a.displayName||b.handle||a.handle||"",avatar:b.avatar||a.avatar||"",images:[...new Set([...(a.images||[]),...(b.images||[])])],externalLinks:[...new Set([...(a.externalLinks||[]),...(b.externalLinks||[])])].slice(0,5),hasVideo:!!(a.hasVideo||b.hasVideo),hasQuote:!!(a.hasQuote||b.hasQuote),stats:mergeStats(a.stats,b.stats),collections:[...new Set([...(a.collections||[]),...(b.collections||[])])],tags:[...new Set([...(a.tags||[]),...(b.tags||[])])],importedAt:b.importedAt||a.importedAt});}
function scheduleSave(){saveQueued=true;if(saveTimer)return;saveTimer=setTimeout(()=>{saveTimer=null;flushSave().catch(console.error);},SAVE_DELAY);}
async function flushSave(){if(!saveQueued)return;saveQueued=false;const items=bookmarkCache||[];const payload=items.map(normalizeItem);savePromise=chrome.storage.local.set({[KEY]:payload,lastSavedAt:new Date().toISOString()});try{await savePromise;}finally{savePromise=null;}if(saveQueued)scheduleSave();}
async function saveBookmarks(items){bookmarkCache=items.map(normalizeItem);if(saveTimer){clearTimeout(saveTimer);saveTimer=null;}saveQueued=true;await flushSave();}
async function syncCacheFromStorage(){if(saveTimer){clearTimeout(saveTimer);saveTimer=null;}if(saveQueued)await flushSave();if(savePromise){try{await savePromise;}catch(error){console.warn(error);}}const data=await chrome.storage.local.get(KEY);bookmarkCache=Array.isArray(data[KEY])?data[KEY].map(normalizeItem):[];return bookmarkCache;}
async function prepareStorageWrite(){if(saveTimer){clearTimeout(saveTimer);saveTimer=null;}saveQueued=false;if(savePromise){try{await savePromise;}catch(error){console.warn(error);}}bookmarkCache=null;}
async function reloadCache(){if(saveTimer){clearTimeout(saveTimer);saveTimer=null;}saveQueued=false;if(savePromise){try{await savePromise;}catch(error){console.warn(error);}}const data=await chrome.storage.local.get(KEY);bookmarkCache=Array.isArray(data[KEY])?data[KEY].map(normalizeItem):[];return bookmarkCache;}
async function clearBookmarks(){if(saveTimer){clearTimeout(saveTimer);saveTimer=null;}saveQueued=false;if(savePromise){try{await savePromise;}catch(error){console.warn(error);}}bookmarkCache=[];await chrome.storage.local.remove([KEY,"lastSavedAt"]);bookmarkCache=[];try{const tabs=await chrome.tabs.query({});for(const t of tabs){if(t.id)chrome.tabs.sendMessage(t.id,{type:"CLEAR_PAGE_CACHE"}).catch(()=>{});}}catch(e){}return true;}
async function mergeBookmarks(items){const existing=await getBookmarks();const map=new Map(existing.filter(item=>item?.tweetId).map(item=>[String(item.tweetId),normalizeItem(item)]));for(const raw of items){if(!raw?.tweetId)continue;const key=String(raw.tweetId),current=map.get(key);map.set(key,current?mergeItem(current,raw):normalizeItem(raw));}bookmarkCache=[...map.values()].sort((a,b)=>(Date.parse(b.createdAt||"")||0)-(Date.parse(a.createdAt||"")||0));scheduleSave();return bookmarkCache.length;}
async function importBookmarks(items){const existing=await syncCacheFromStorage();const map=new Map(existing.filter(item=>item?.tweetId).map(item=>[String(item.tweetId),normalizeItem(item)]));for(const raw of items){if(!raw?.tweetId||!raw?.tweetUrl)continue;const key=String(raw.tweetId),current=map.get(key);map.set(key,current?mergeItem(current,raw):normalizeItem(raw));}const merged=[...map.values()].sort((a,b)=>(Date.parse(b.createdAt||"")||0)-(Date.parse(a.createdAt||"")||0));await saveBookmarks(merged);return{count:merged.length,existing:existing.length,incoming:items.length};}
chrome.runtime.onMessage.addListener((message,sender,sendResponse)=>{if(message?.type==="BOOKMARK_BATCH"){mergeBookmarks(message.items||[]).then(count=>sendResponse({ok:true,count})).catch(error=>{console.error(error);sendResponse({ok:false,error:String(error)});});return true;}if(message?.type==="SAVE_BOOKMARKS"){saveBookmarks(Array.isArray(message.items)?message.items:[]).then(()=>sendResponse({ok:true,count:Array.isArray(message.items)?message.items.length:0})).catch(error=>{console.error(error);sendResponse({ok:false,error:String(error)});});return true;}if(message?.type==="IMPORT_BOOKMARKS"){importBookmarks(Array.isArray(message.items)?message.items:[]).then(result=>sendResponse({ok:true,...result})).catch(error=>{console.error(error);sendResponse({ok:false,error:String(error)});});return true;}if(message?.type==="CLEAR_BOOKMARKS"){clearBookmarks().then(()=>sendResponse({ok:true})).catch(error=>{console.error(error);sendResponse({ok:false,error:String(error)});});return true;}if(message?.type==="PREPARE_STORAGE_WRITE"){prepareStorageWrite().then(()=>sendResponse({ok:true})).catch(error=>{console.error(error);sendResponse({ok:false,error:String(error)});});return true;}if(message?.type==="RELOAD_CACHE"){reloadCache().then(items=>sendResponse({ok:true,count:items.length})).catch(error=>{console.error(error);sendResponse({ok:false,error:String(error)});});return true;}if(message?.type==="BOOKMARK_PROGRESS")chrome.runtime.sendMessage(message).catch(()=>{});});
