let scanning=false;
let stopRequested=false;
let seen=new Set();
let snapshots=new Map();
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));

// SPEED TUNING: Aggressive scroll jumps and minimized wait thresholds
const SCROLL_FACTOR=0.85;
const MIN_SCROLL=1000;
const SCROLL_WAIT=40;         // Quick pause for DOM scroll update
const LOADING_WAIT=120;       // Pauses only when X network skeleton/spinner is visible
const RECOVERY_WAIT=100;      // Nudge pause when feed seems stalled

function getCollection(){if(/^\/i\/(bookmarks|history)\/?$/.test(location.pathname))return"bookmark";if(/^\/i\/history\/likes\/?$/.test(location.pathname))return"like";return null;}
function collectionName(collection){return collection==="like"?"Likes":"Bookmarks";}
function topLevelTweets(){return[...document.querySelectorAll('article[data-testid="tweet"], article[role="article"]')].filter(article=>!article.parentElement?.closest('article[data-testid="tweet"], article[role="article"]'));}
function parseStats(article){const label=article.querySelector('[role="group"]')?.getAttribute("aria-label")||"";const get=pattern=>{const match=label.match(pattern);return match?Number(match[1].replace(/,/g,"")):0;};return{replies:get(/([\d,]+)\s+repl(?:y|ies)/i),reposts:get(/([\d,]+)\s+reposts?/i),likes:get(/([\d,]+)\s+likes?/i),bookmarks:get(/([\d,]+)\s+bookmarks?/i),views:get(/([\d,]+)\s+views?/i)};}
function normalizeMediaUrl(value){const raw=String(value||"").trim();if(!raw||/^(data:|blob:|javascript:)/i.test(raw))return"";try{const url=new URL(raw,location.href);return/^https?:$/i.test(url.protocol)?url.href:"";}catch{return"";}}
function addImageCandidate(set,value){const url=normalizeMediaUrl(value);if(url)set.add(url);}
function addSrcsetCandidates(set,srcset){String(srcset||"").split(",").map(part=>part.trim().split(/\s+/)[0]).filter(Boolean).forEach(url=>addImageCandidate(set,url));}
function extractImageUrls(article){const urls=new Set();const mediaRoots=[...article.querySelectorAll("[data-testid=\"tweetPhoto\"]")];for(const a of article.querySelectorAll("a[href*=\"/photo/\"]")){if(a.closest("[data-testid=\"tweetPhoto\"]"))continue;mediaRoots.push(a);}for(const root of mediaRoots){for(const node of root.querySelectorAll("img,source")){addImageCandidate(urls,node.currentSrc);addImageCandidate(urls,node.src);addImageCandidate(urls,node.getAttribute?.("src"));addImageCandidate(urls,node.getAttribute?.("data-src"));addImageCandidate(urls,node.getAttribute?.("data-lazy-src"));addImageCandidate(urls,node.getAttribute?.("data-original"));addSrcsetCandidates(urls,node.getAttribute?.("srcset"));addSrcsetCandidates(urls,node.getAttribute?.("data-srcset"));}const href=root.getAttribute?.("href");if(href&&/\/photo\//i.test(href))addImageCandidate(urls,href);for(const a of root.querySelectorAll("a[href]")){const href=a.href||"";if(/\/photo\//i.test(href)&&/pbs\.twimg\.com\//i.test(href))addImageCandidate(urls,href);}}for(const v of article.querySelectorAll("[data-testid=\"videoPlayer\"],[data-testid=\"videoComponent\"],video")){if(v.tagName==="VIDEO"){addImageCandidate(urls,v.poster);addImageCandidate(urls,v.getAttribute?.("poster"));addImageCandidate(urls,v.currentSrc);}for(const vid of v.querySelectorAll("video")){addImageCandidate(urls,vid.poster);addImageCandidate(urls,vid.getAttribute?.("poster"));addImageCandidate(urls,vid.currentSrc);}for(const node of v.querySelectorAll("img,source")){addImageCandidate(urls,node.currentSrc);addImageCandidate(urls,node.src);addImageCandidate(urls,node.getAttribute?.("src"));addImageCandidate(urls,node.getAttribute?.("data-src"));addImageCandidate(urls,node.getAttribute?.("data-lazy-src"));addImageCandidate(urls,node.getAttribute?.("data-original"));addSrcsetCandidates(urls,node.getAttribute?.("srcset"));addSrcsetCandidates(urls,node.getAttribute?.("data-srcset"));}}return[...urls].filter(src=>{try{const u=new URL(src);return u.hostname==="pbs.twimg.com"&&/^\/(?:media|ext_tw_video_thumb|amplify_video_thumb|tweet_video_thumb)\//i.test(u.pathname);}catch{return false}});}
function mergeStats(a={},b={}){const keys=["replies","reposts","likes","bookmarks","views"];return Object.fromEntries(keys.map(key=>[key,Math.max(Number(a[key]||0),Number(b[key]||0))]));}
function mergeTweet(a,b){return{...a,...b,text:b.text||a.text||"",displayName:b.displayName||a.displayName||b.handle||a.handle||"",avatar:b.avatar||a.avatar||"",images:[...new Set([...(a.images||[]),...(b.images||[])])],externalLinks:[...new Set([...(a.externalLinks||[]),...(b.externalLinks||[])])].slice(0,5),hasVideo:!!(a.hasVideo||b.hasVideo),hasQuote:!!(a.hasQuote||b.hasQuote),stats:mergeStats(a.stats,b.stats),collections:[...new Set([...(a.collections||[]),...(b.collections||[])])],importedAt:b.importedAt||a.importedAt};}
function materiallyChanged(a,b){return a.text!==b.text||a.displayName!==b.displayName||a.avatar!==b.avatar||a.hasVideo!==b.hasVideo||a.hasQuote!==b.hasQuote||JSON.stringify(a.images||[])!==JSON.stringify(b.images||[])||JSON.stringify(a.externalLinks||[])!==JSON.stringify(b.externalLinks||[])||JSON.stringify(a.stats||{})!==JSON.stringify(b.stats||{});}
function parseTweet(article,collection){const statusLink=[...article.querySelectorAll('a[href*="/status/"]')].map(a=>a.href).find(href=>/\/(?:status)\/\d+/.test(href));if(!statusLink)return null;const match=statusLink.match(/(?:x\.com|twitter\.com)\/([^/]+)\/status\/(\d+)/i);if(!match)return null;const[,handle,tweetId]=match;const text=article.querySelector('[data-testid="tweetText"]')?.innerText?.trim()||"";const time=article.querySelector('time');const createdAt=time?.dateTime||"";const userCell=article.querySelector('[data-testid="User-Name"]');const displayName=userCell?.querySelector('div[dir="ltr"]')?.innerText?.trim()||userCell?.innerText?.split('\n')[0]?.trim()||handle;const avatar=article.querySelector('[data-testid="Tweet-User-Avatar"] img')?.currentSrc||article.querySelector('[data-testid="Tweet-User-Avatar"] img')?.src||"";const images=extractImageUrls(article);const hasVideo=!!article.querySelector('[data-testid="videoPlayer"], video');const hasQuote=!!article.querySelector('[data-testid="quoteTweet"], article article');const textNode=article.querySelector("[data-testid=\"tweetText\"]");const externalLinks=[...(textNode?.querySelectorAll("a[href]")||[])].map(a=>a.href).filter(href=>href&&!href.includes("x.com/")&&!href.includes("twitter.com/")&&!href.startsWith("javascript:"));return{tweetId,handle,displayName,text,createdAt,tweetUrl:`https://x.com/${handle}/status/${tweetId}`,avatar,images,hasVideo,hasQuote,externalLinks:[...new Set(externalLinks)].slice(0,5),stats:parseStats(article),collections:[collection],importedAt:new Date().toISOString()};}
function collectVisible(collection){const items=[];for(const article of topLevelTweets()){const item=parseTweet(article,collection);if(!item)continue;const previous=snapshots.get(item.tweetId);const merged=previous?mergeTweet(previous,item):item;if(!previous){seen.add(item.tweetId);items.push(item);}else if(materiallyChanged(previous,merged))items.push(merged);snapshots.set(item.tweetId,merged);}return items;}
async function emitBatch(items){if(!items.length)return;await chrome.runtime.sendMessage({type:"BOOKMARK_BATCH",items}).catch(()=>{});}
async function emitProgress(extra={}){await chrome.runtime.sendMessage({type:"BOOKMARK_PROGRESS",scanned:seen.size,url:location.href,...extra}).catch(()=>{});}
function getScrollMetrics(){const scrollTop=window.scrollY||document.documentElement.scrollTop||document.body.scrollTop||0;const viewport=window.innerHeight||document.documentElement.clientHeight||1;const height=Math.max(document.documentElement.scrollHeight,document.body?.scrollHeight||0);return{scrollTop,viewport,height,distanceToBottom:height-(scrollTop+viewport)};}
function pageIsLoading(){return!!document.querySelector('[role="progressbar"], [data-testid="tweetSkeleton"]');}
async function scrollForMore(collection){const before=getScrollMetrics();const step=Math.max(Math.floor(before.viewport*SCROLL_FACTOR),MIN_SCROLL);window.scrollBy({top:step,behavior:"auto"});await sleep(SCROLL_WAIT);if(pageIsLoading())await sleep(LOADING_WAIT);const items=collectVisible(collection);return{before,after:getScrollMetrics(),items};}

let mediaObserver=null;let mediaObserverTimer=null;function startMediaObserver(collection){if(mediaObserver)mediaObserver.disconnect();mediaObserver=new MutationObserver(()=>{if(!scanning||mediaObserverTimer)return;mediaObserverTimer=setTimeout(async()=>{mediaObserverTimer=null;const items=collectVisible(collection);if(items.length)await emitBatch(items);},50);});mediaObserver.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["src","srcset","data-src","data-lazy-src","style"]});}function stopMediaObserver(){if(mediaObserver)mediaObserver.disconnect();mediaObserver=null;if(mediaObserverTimer){clearTimeout(mediaObserverTimer);mediaObserverTimer=null;}}

async function scanAll(){if(scanning)return;const collection=getCollection();if(!collection){await emitProgress({status:"error",message:"Open X Bookmarks or X Likes first: x.com/i/history, x.com/i/bookmarks, or x.com/i/history/likes"});return;}scanning=true;stopRequested=false;seen=new Set();snapshots=new Map();startMediaObserver(collection);await emitProgress({status:"running",message:`Scanning X ${collectionName(collection)}...`});let idleRounds=0,lastCount=0,lastHeight=0;const safetyDeadline=Date.now()+45*60*1000;try{let batch=collectVisible(collection);if(batch.length)await emitBatch(batch);for(let round=0;!stopRequested&&Date.now()<safetyDeadline;round++){const beforeCount=seen.size;const metrics=await scrollForMore(collection);if(metrics.items.length)await emitBatch(metrics.items);const countChanged=seen.size>beforeCount;const pageChanged=metrics.after.height!==metrics.before.height||metrics.after.scrollTop!==metrics.before.scrollTop;const noMovementAtBottom=metrics.after.distanceToBottom<=8&&metrics.after.height===metrics.before.height&&metrics.after.scrollTop===metrics.before.scrollTop;const loading=pageIsLoading();if(countChanged||pageChanged||loading)idleRounds=0;else idleRounds++;if(metrics.after.distanceToBottom<=15&&loading){await sleep(LOADING_WAIT);const more=collectVisible(collection);if(more.length){await emitBatch(more);idleRounds=0;}}if(seen.size===lastCount&&metrics.after.height===lastHeight&&noMovementAtBottom&&!loading)idleRounds++;lastCount=seen.size;lastHeight=metrics.after.height;if(round%3===0||seen.size!==beforeCount)emitProgress({status:"running",message:`Found ${seen.size} ${collectionName(collection).toLowerCase()}...`});if(idleRounds>=4)break;
if(idleRounds>=2){window.scrollBy({top:Math.max(Math.floor(window.innerHeight*.8),600),behavior:"auto"});await sleep(RECOVERY_WAIT);}}const finalBatch=collectVisible(collection);if(finalBatch.length)await emitBatch(finalBatch);const timedOut=Date.now()>=safetyDeadline;await emitProgress({status:stopRequested?"stopped":timedOut?"timeout":"done",message:stopRequested?`Stopped at ${seen.size} ${collectionName(collection).toLowerCase()}.`:timedOut?`Scanner safety limit reached at ${seen.size} ${collectionName(collection).toLowerCase()}. The archive is saved; you can continue scanning.`:`Finished: ${seen.size} ${collectionName(collection).toLowerCase()} found.`});}finally{stopMediaObserver();scanning=false;}}

chrome.runtime.onMessage.addListener((message,sender,sendResponse)=>{if(message?.type==="CLEAR_PAGE_CACHE"){seen=new Set();snapshots=new Map();sendResponse({ok:true});return true;}if(message?.type==="SCAN_BOOKMARKS"){scanAll();sendResponse({ok:true});}if(message?.type==="STOP_SCAN"){stopRequested=true;sendResponse({ok:true});}if(message?.type==="GET_PAGE_STATE"){sendResponse({ok:true,collection:getCollection(),url:location.href,scanning});}if(message?.type==="FETCH_TWEET_IMAGE"){(async()=>{const target=String(message.tweetId||"");let found=null;for(let i=0;i<10&&!found;i++){for(const article of topLevelTweets()){const item=parseTweet(article,"bookmark");if(item&&String(item.tweetId)===target){found=item;if(item.images?.length)break;}}if(found?.images?.length)break;await sleep(200);}sendResponse({ok:!!found,item:found||null});})().catch(error=>sendResponse({ok:false,error:String(error)}));return true;}return true;});