const $=selector=>document.querySelector(selector);
const state={bookmarks:[],query:"",filter:"all",collection:"all",tagFilter:"",index:[],parsed:null,scanActive:false,allTags:[]};
const normalize=value=>String(value||"").toLowerCase().normalize("NFKC");
const escapeHtml=value=>String(value||"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
function cleanStoredImages(value){return[...new Set((Array.isArray(value)?value:[]).filter(src=>{try{const u=new URL(String(src));if(u.hostname.endsWith("abs.twimg.com"))return false;if(u.hostname.endsWith("video.twimg.com"))return false;if(u.hostname==="pbs.twimg.com"&&!/^\/(?:media|ext_tw_video_thumb|amplify_video_thumb|tweet_video_thumb)\//i.test(u.pathname))return false;return true;}catch{return false}}))];}function collections(item){const values=Array.isArray(item?.collections)?item.collections.filter(v=>v==="bookmark"||v==="like"):[];return values.length?[...new Set(values)]:["bookmark"];}
function normalizeItem(item){return{...item,images:cleanStoredImages(item?.images),collections:collections(item),tags:Array.isArray(item?.tags)?[...new Set(item.tags.map(t=>String(t).trim()).filter(Boolean))]:[]};};
function collectAllTags(){const tagSet=new Set();for(const item of state.bookmarks){if(Array.isArray(item.tags))for(const t of item.tags)tagSet.add(t);}state.allTags=[...tagSet].sort((a,b)=>a.localeCompare(b));populateTagFilter();}
function populateTagFilter(){const select=$("#tagFilter");if(!select)return;const current=select.value;select.innerHTML='<option value="">All tags</option>';for(const tag of state.allTags){const opt=document.createElement("option");opt.value=tag;opt.textContent=tag;select.appendChild(opt);}select.value=current||"";}
function buildIndex(){state.index=state.bookmarks.map(item=>({item,text:normalize(item.text),author:normalize(`${item.handle} ${item.displayName}`),url:normalize(`${item.tweetUrl} ${(item.externalLinks||[]).join(" ")}`),tags:normalize((item.tags||[]).join(" ")),all:normalize([item.text,item.handle,item.displayName,item.tweetUrl,...(item.externalLinks||[]),...(item.tags||[])].join(" "))}));}
function parseQuery(raw){const query=String(raw||"").trim(),operators={from:"",before:null,after:null,media:null,tags:[]},phrases=[],terms=[];let rest=query.replace(/"([^"]+)"/g,(_,phrase)=>(phrase.trim()&&phrases.push(phrase.trim())," "));rest=rest.replace(/(^|\s)from:@?([\w.]+)(?=\s|$)/gi,(_,lead,value)=>(operators.from=normalize(value),lead));rest=rest.replace(/(^|\s)tag:([\w._-]+)(?=\s|$)/gi,(_,lead,value)=>{operators.tags.push(normalize(value.trim()));return lead;});rest=rest.replace(/(^|\s)has:(text|image|images|multi(?:ple)?-?images|video|link)(?=\s|$)/gi,(_,lead,value)=>{const v=value.toLowerCase();const compact=v.replace(/-/g,"");operators.media=compact==="images"||compact==="multiimages"||compact==="multipleimages"?"multiple-images":v==="text"?"text":v;return lead;});rest=rest.replace(/(^|\s)(before|after):(\d{4}-\d{2}-\d{2})(?=\s|$)/gi,(_,lead,type,value)=>{const date=new Date(`${value}T00:00:00`);if(!Number.isNaN(date.getTime()))operators[type.toLowerCase()]=date;return lead});for(const token of rest.split(/\s+/).map(normalize).filter(Boolean))if(token!=="and")terms.push(token);return{raw:query,terms:[...new Set(terms)],phrases:[...new Set(phrases.map(normalize))],operators};}
function matches(entry,parsed){const{item,all}=entry,{terms,phrases,operators}=parsed;if(state.collection!=="all"&&!collections(item).includes(state.collection))return false;if(state.tagFilter&&!(item.tags||[]).some(t=>normalize(t)===normalize(state.tagFilter)))return false;if(operators.from&&!normalize(item.handle).replace(/^@/,"").includes(operators.from))return false;if(operators.tags.length){const itemTags=(item.tags||[]).map(normalize);if(operators.tags.some(t=>!itemTags.includes(t)))return false;}const created=new Date(item.createdAt||0);if(operators.before&&!(created<operators.before))return false;if(operators.after){const start=new Date(operators.after);start.setHours(0,0,0,0);if(!(created>=start))return false}if(operators.media==="text"&&((item.images||[]).length||item.hasVideo||(item.externalLinks||[]).length))return false;if(operators.media==="image"&&!(item.images||[]).length)return false;if(operators.media==="multiple-images"&&((item.images||[]).length<2))return false;if(operators.media==="video"&&!item.hasVideo)return false;if(operators.media==="link"&&!(item.externalLinks||[]).length)return false;if(phrases.some(phrase=>!all.includes(phrase)))return false;if(terms.some(term=>!all.includes(term)))return false;return true;}
function formatDate(value){const date=new Date(value);return Number.isNaN(date.getTime())?"":date.toLocaleString([],{year:"numeric",month:"short",day:"numeric"});}
function searchTerms(parsed){return[...parsed.terms,...parsed.phrases].filter(Boolean).sort((a,b)=>b.length-a.length);}
function highlight(text,parsed){const safe=escapeHtml(text||"[No text]"),terms=searchTerms(parsed);if(!terms.length)return safe;const pattern=terms.map(term=>term.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")).join("|");return pattern?safe.replace(new RegExp(`(${pattern})`,"gi"),"<mark>$1</mark>"):safe;}
function visible(){state.parsed=parseQuery(state.query);return state.index.filter(entry=>matches(entry,state.parsed)).filter(entry=>{const item=entry.item,hasImages=(item.images||[]).length>0,hasMultipleImages=(item.images||[]).length>1,hasVideo=!!item.hasVideo,hasLinks=(item.externalLinks||[]).length>0;if(state.filter==="text")return!hasImages&&!hasVideo&&!hasLinks;if(state.filter==="image")return hasImages;if(state.filter==="multiple-images")return hasMultipleImages;if(state.filter==="video")return hasVideo;if(state.filter==="link")return hasLinks;return true}).map(entry=>entry.item);}
function collectionLabel(item){const c=collections(item);return c.length===2?"BOOKMARKED + LIKED":c[0]==="like"?"LIKED":"BOOKMARKED";}
function mediaVariants(url){const raw=String(url||"");if(!raw)return[];const out=[raw];if(!/pbs\.twimg\.com\/media\//i.test(raw))return out;const add=v=>{if(v&&!out.includes(v))out.push(v)};const setName=(name)=>{try{const u=new URL(raw);u.searchParams.set("name",name);return u.href;}catch{return""}};add(setName("medium"));add(setName("large"));add(setName("orig"));return out;}
function bindMediaFallbacks(){document.querySelectorAll(".media[data-base]:not([data-bound])").forEach(img=>{img.dataset.bound="1";const variants=mediaVariants(img.dataset.base);let index=0;const loadNext=()=>{if(index>=variants.length){img.closest(".mediaWrap")?.classList.add("imageFailed");return;}img.src=variants[index++];};img.addEventListener("error",loadNext);loadNext();});}
function tagChipsHtml(item){const tags=item.tags||[];let html='<div class="tagList">';for(const tag of tags){html+=`<span class="tagChip">${escapeHtml(tag)}<span class="tagRemove" data-tweet-id="${escapeHtml(item.tweetId)}" data-tag="${escapeHtml(tag)}" title="Remove tag">×</span></span>`;}html+=`<span class="addTagBtn" data-tweet-id="${escapeHtml(item.tweetId)}" title="Add tag">+ tag</span>`;html+='</div>';return html;}
function card(item){const parsed=state.parsed||parseQuery(state.query),image=item.images?.[0]?`<div class="mediaWrap"><img class="media" data-base="${escapeHtml(item.images[0])}" loading="lazy" decoding="async" alt=""></div>`:"";const stats=item.stats||{},media=[item.hasVideo?"Video":"",item.images?.length?`${item.images.length} image${item.images.length>1?"s":""}`:"",(item.externalLinks||[]).length?"Link":""].filter(Boolean);return`<article class="card" data-url="${escapeHtml(item.tweetUrl)}" role="link" tabindex="0" title="Open post on X">${image}<div class="body"><div class="who">${item.avatar?`<img class="avatar" src="${escapeHtml(item.avatar)}" loading="lazy" decoding="async" alt="">`:`<div class="avatar"></div>`}<div><div class="name">${escapeHtml(item.displayName)}</div><div class="handle">@${escapeHtml(item.handle)}</div></div></div><div class="text">${highlight(item.text,parsed)}</div><div class="meta"><span class="collectionBadge">${collectionLabel(item)}</span><span>${escapeHtml(formatDate(item.createdAt))}</span><span>♥ ${Number(stats.likes||0).toLocaleString()}</span><span>↻ ${Number(stats.reposts||0).toLocaleString()}</span>${media.map(value=>`<span>${escapeHtml(value)}</span>`).join("")}</div>${tagChipsHtml(item)}</div></article>`;}
function render(){const items=visible(),total=state.bookmarks.length;$("#count").textContent=total.toLocaleString();$("#resultCount").textContent=`${items.length.toLocaleString()} result${items.length===1?"":"s"}`;$("#grid").innerHTML=items.map(card).join("");bindMediaFallbacks();bindTagActions();$("#empty").classList.toggle("hidden",items.length>0);if(!items.length)$("#empty").textContent=total?"No saved posts match this search.":"No saved posts yet.";const parsed=state.parsed,operatorParts=[];if(parsed.operators.from)operatorParts.push(`from:@${parsed.operators.from}`);if(parsed.operators.after)operatorParts.push(`after:${parsed.operators.after.toISOString().slice(0,10)}`);if(parsed.operators.before)operatorParts.push(`before:${parsed.operators.before.toISOString().slice(0,10)}`);if(parsed.operators.media)operatorParts.push(`has:${parsed.operators.media}`);for(const t of parsed.operators.tags)operatorParts.push(`tag:${t}`);const collectionText=state.collection==="bookmark"?"bookmarks":state.collection==="like"?"likes":"saved posts";$("#searchInfo").textContent=state.query.trim()?`Searching ${operatorParts.concat(parsed.terms,parsed.phrases.map(value=>`"${value}"`)).join(" ")}`:`Showing ${items.length.toLocaleString()} ${collectionText}`;}
/* ── Tag CRUD ── */
let tagModalTweetId=null;
function openTagModal(tweetId){const item=state.bookmarks.find(b=>String(b.tweetId)===String(tweetId));if(!item)return;tagModalTweetId=tweetId;renderTagModalCurrent(item);renderTagSuggestions(item);$("#tagInput").value="";$("#tagModal").classList.remove("hidden");$("#tagModal").setAttribute("aria-hidden","false");setTimeout(()=>$("#tagInput").focus(),50);}
function closeTagModal(){tagModalTweetId=null;$("#tagModal").classList.add("hidden");$("#tagModal").setAttribute("aria-hidden","true");}
function renderTagModalCurrent(item){const container=$("#tagModalCurrentTags");const tags=item.tags||[];if(!tags.length){container.innerHTML='<span style="color:#6f7781;font-size:11px;">No tags yet</span>';return;}container.innerHTML=tags.map(tag=>`<span class="tagChip">${escapeHtml(tag)}<span class="tagRemove" data-tag="${escapeHtml(tag)}" title="Remove tag">×</span></span>`).join("");}
function renderTagSuggestions(item){const container=$("#tagSuggestions");const existing=new Set((item.tags||[]).map(normalize));const suggestions=state.allTags.filter(t=>!existing.has(normalize(t)));if(!suggestions.length){container.innerHTML='';return;}container.innerHTML=suggestions.slice(0,15).map(tag=>`<span class="tagSuggestion" data-tag="${escapeHtml(tag)}">${escapeHtml(tag)}</span>`).join("");}
async function addTagToTweet(tweetId,tagName){const tag=String(tagName).trim().toLowerCase().replace(/[^a-z0-9_-]/g,"");if(!tag||tag.length>30)return;const data=await chrome.storage.local.get("bookmarks");const bookmarks=Array.isArray(data.bookmarks)?data.bookmarks:[];const item=bookmarks.find(b=>String(b?.tweetId)===String(tweetId));if(!item)return;const tags=Array.isArray(item.tags)?[...item.tags]:[];if(tags.some(t=>normalize(t)===normalize(tag)))return;tags.push(tag);item.tags=tags;await chrome.storage.local.set({bookmarks,lastSavedAt:new Date().toISOString()});}
async function removeTagFromTweet(tweetId,tagName){const data=await chrome.storage.local.get("bookmarks");const bookmarks=Array.isArray(data.bookmarks)?data.bookmarks:[];const item=bookmarks.find(b=>String(b?.tweetId)===String(tweetId));if(!item)return;item.tags=(item.tags||[]).filter(t=>normalize(t)!==normalize(tagName));await chrome.storage.local.set({bookmarks,lastSavedAt:new Date().toISOString()});}
function bindTagActions(){document.querySelectorAll(".addTagBtn:not([data-bound])").forEach(btn=>{btn.dataset.bound="1";btn.addEventListener("click",e=>{e.stopPropagation();e.preventDefault();openTagModal(btn.dataset.tweetId);});});document.querySelectorAll(".tagList .tagRemove:not([data-bound])").forEach(btn=>{btn.dataset.bound="1";btn.addEventListener("click",async e=>{e.stopPropagation();e.preventDefault();await removeTagFromTweet(btn.dataset.tweetId,btn.dataset.tag);});});}
/* ── Tag modal event handlers ── */
function handleTagModalRemove(e){const btn=e.target.closest(".tagRemove[data-tag]");if(!btn||!tagModalTweetId)return;removeTagFromTweet(tagModalTweetId,btn.dataset.tag);}
async function handleAddTag(){const input=$("#tagInput"),value=input.value.trim();if(!value||!tagModalTweetId)return;await addTagToTweet(tagModalTweetId,value);input.value="";input.focus();}
function handleTagSuggestionClick(e){const btn=e.target.closest(".tagSuggestion[data-tag]");if(!btn||!tagModalTweetId)return;addTagToTweet(tagModalTweetId,btn.dataset.tag);}
$("#tagModalClose").addEventListener("click",closeTagModal);
$(".tagModalBackdrop").addEventListener("click",closeTagModal);
$("#tagModalCurrentTags").addEventListener("click",handleTagModalRemove);
$("#tagAddBtn").addEventListener("click",handleAddTag);
$("#tagInput").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();handleAddTag();}});
$("#tagSuggestions").addEventListener("click",handleTagSuggestionClick);
/* ── Core lifecycle ── */
async function load(){const data=await chrome.storage.local.get(["bookmarks","lastSavedAt"]);state.bookmarks=(Array.isArray(data.bookmarks)?data.bookmarks:[]).map(normalizeItem);collectAllTags();buildIndex();render();if(data.lastSavedAt){const date=new Date(data.lastSavedAt);$("#saveState").textContent=Number.isNaN(date.getTime())?"Auto-save on":`Saved ${date.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}`;}else $("#saveState").textContent="Auto-save on";updatePageUI();if(tagModalTweetId){const item=state.bookmarks.find(b=>String(b.tweetId)===String(tagModalTweetId));if(item){renderTagModalCurrent(item);renderTagSuggestions(item);}}}
function mergeByTweetId(existing,incoming){const map=new Map();for(const raw of [...existing,...incoming]){if(!raw?.tweetId)continue;const item=normalizeItem(raw),key=String(item.tweetId),current=map.get(key);map.set(key,current?{...current,...item,collections:[...new Set([...(current.collections||[]),...(item.collections||[])])],tags:[...new Set([...(current.tags||[]),...(item.tags||[])])]}:item);}return[...map.values()].sort((a,b)=>(Date.parse(b.createdAt||"")||0)-(Date.parse(a.createdAt||"")||0));}
function validateBookmarks(value){const raw=Array.isArray(value)?value:value?.bookmarks;if(!Array.isArray(raw))throw new Error("JSON must contain a bookmarks array.");const valid=raw.filter(item=>item&&item.tweetId&&item.tweetUrl);if(!valid.length&&raw.length)throw new Error("No valid saved posts found. Each post needs tweetId and tweetUrl.");return valid.map(normalizeItem);}
async function exportBookmarks(){const data=await chrome.storage.local.get("bookmarks"),bookmarks=Array.isArray(data.bookmarks)?data.bookmarks.map(normalizeItem):[];const payload=JSON.stringify({format:"x-bookmark-library",version:2,exportedAt:new Date().toISOString(),count:bookmarks.length,bookmarks},null,2);const url=URL.createObjectURL(new Blob([payload],{type:"application/json"})),link=document.createElement("a");link.href=url;link.download=`x-bookmarks-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$("#status").textContent=`Exported ${bookmarks.length.toLocaleString()} saved posts as JSON.`;}
async function importBookmarks(file){if(!file)return;try{const parsed=JSON.parse(await file.text()),incoming=validateBookmarks(parsed),data=await chrome.storage.local.get("bookmarks"),existing=Array.isArray(data.bookmarks)?data.bookmarks.map(normalizeItem):[],merged=mergeByTweetId(existing,incoming);const result=await chrome.runtime.sendMessage({type:"SAVE_BOOKMARKS",items:merged});if(!result?.ok)throw new Error(result?.error||"Storage import failed.");const added=merged.length-existing.length;await load();$("#status").textContent=`Imported ${incoming.length.toLocaleString()} saved posts. ${Math.max(0,added).toLocaleString()} new, ${Math.max(0,incoming.length-Math.max(0,added)).toLocaleString()} merged.`;}catch(error){$("#status").textContent=`Import failed: ${error.message||error}`;}finally{$("#importFile").value="";}}
async function activeTab(){const[tab]=await chrome.tabs.query({active:true,currentWindow:true});return tab;}
function pageCollection(url){try{const path=new URL(url).pathname;if(/^\/i\/(bookmarks|history)\/?$/.test(path))return"bookmark";if(/^\/i\/history\/likes\/?$/.test(path))return"like";}catch{}return null;}
async function updatePageUI(){if(state.scanActive)return;const tab=await activeTab(),collection=pageCollection(tab?.url||"");$("#scanBtn").textContent=collection==="like"?"Scan X Likes":collection==="bookmark"?"Scan X Bookmarks":"Scan Current X Page";$("#status").innerHTML=collection?`Ready to scan <b>${collection==="like"?"X Likes":"X Bookmarks"}</b>.`:`Open <b>x.com/i/history</b>, <b>x.com/i/bookmarks</b>, or <b>x.com/i/history/likes</b>, then scan.`;}
async function sendToActive(type){const tab=await activeTab();if(!tab?.id)return;try{await chrome.tabs.sendMessage(tab.id,{type});}catch{$("#status").innerHTML="Open an X Bookmarks or Likes page first, then reload it once after installing the extension.";}}
$("#scanBtn").addEventListener("click",async()=>{const tab=await activeTab(),collection=pageCollection(tab?.url||"");if(!collection){$("#status").innerHTML="Open <b>x.com/i/history</b>, <b>x.com/i/bookmarks</b>, or <b>x.com/i/history/likes</b> first.";return;}state.scanActive=true;$("#status").textContent=`Starting scanner... ${collection==="like"?"Likes":"Bookmarks"} are auto-saved as they are collected.`;await sendToActive("SCAN_BOOKMARKS");});
$("#stopBtn").addEventListener("click",()=>sendToActive("STOP_SCAN"));$("#showcaseBtn").addEventListener("click",()=>chrome.tabs.create({url:chrome.runtime.getURL("showcase.html")}));$("#importBtn").addEventListener("click",()=>$("#importFile").click());$("#importFile").addEventListener("change",e=>importBookmarks(e.target.files?.[0]));$("#exportBtn").addEventListener("click",exportBookmarks);$("#openBookmarks").addEventListener("click",()=>chrome.tabs.create({url:"https://x.com/i/bookmarks"}));$("#openLikes").addEventListener("click",()=>chrome.tabs.create({url:"https://x.com/i/history/likes"}));
$("#clearBtn").addEventListener("click",async()=>{if(!confirm("Clear the local X Bookmark Library archive? This cannot be undone unless you have an exported JSON backup."))return;try{await chrome.runtime.sendMessage({type:"CLEAR_BOOKMARKS"});}catch(e){console.warn(e);}await chrome.storage.local.remove(["bookmarks","lastSavedAt"]);state.bookmarks=[];state.index=[];state.allTags=[];collectAllTags();render();try{await sendToActive("CLEAR_PAGE_CACHE");}catch(e){}await load();$("#status").textContent="Local archive cleared.";});$("#clearSearch").addEventListener("click",()=>{state.query="";$("#search").value="";render();$("#search").focus();});$("#search").addEventListener("input",e=>{state.query=e.target.value;render();});$("#filter").addEventListener("change",e=>{state.filter=e.target.value;render();});$("#collection").addEventListener("change",e=>{state.collection=e.target.value;render();});$("#tagFilter").addEventListener("change",e=>{state.tagFilter=e.target.value;render();});
$("#grid").addEventListener("click",event=>{const card=event.target.closest(".card[data-url]");if(!card)return;if(event.target.closest(".addTagBtn")||event.target.closest(".tagRemove")||event.target.closest(".tagChip"))return;chrome.tabs.create({url:card.dataset.url});});$("#grid").addEventListener("keydown",event=>{if(event.key!=="Enter"&&event.key!==" ")return;const card=event.target.closest(".card[data-url]");if(!card)return;event.preventDefault();chrome.tabs.create({url:card.dataset.url});});
chrome.runtime.onMessage.addListener(message=>{if(message?.type==="BOOKMARK_PROGRESS"){if(message.status==="running")state.scanActive=true;if(["done","stopped","timeout","error"].includes(message.status))state.scanActive=false;$("#status").textContent=message.message||"Working...";}});chrome.storage.onChanged.addListener(changes=>{if(changes.bookmarks||changes.lastSavedAt)load();});chrome.tabs?.onActivated?.addListener(updatePageUI);chrome.tabs?.onUpdated?.addListener(updatePageUI);load();
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeTagModal();});
